In [4]:
#Import numpy as np and print the version number.Import numpy as np and print the version number.
import numpy as np
np.__version__

'1.18.1'

In [5]:
#Create a 1D array of numbers from 0 to 9Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Create a 3×3 numpy array of all True’s
np.full((3,3), True, dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
#Create a 3×3 numpy array of all True’s
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
#Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [9]:
#Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
#Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
#Convert a 1D array to a 2D array with 2 rows
np.arange(10)
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
#Stack arrays a and b vertically
a = [1,2,3,4]
b = [5,6,7,8]
np.vstack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#Stack arrays a and b horizontally
a = [1,2,3,4]
b = [5,6,7,8]
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
#Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [23]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [24]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [28]:
#Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [31]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [34]:
#Swap columns 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [35]:
#Swap rows 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr
arr[[1,0,2],: ]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [36]:
#Reverse the rows of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [37]:
#Reverse the columns of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [38]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10
arr = np.arange(9).reshape(3,3)
np.random.uniform(5,10,size=(5,3))

array([[9.7063069 , 5.34616634, 5.09839412],
       [6.97891083, 8.85673323, 7.29348736],
       [6.93883767, 5.50751671, 6.90694011],
       [6.74536563, 9.2474997 , 8.56929132],
       [8.22807467, 6.43374611, 6.18886473]])

In [42]:
#Print or show only 3 decimal places of the numpy array rand_arr
rand_arr = np.random.random((5,3))
rand_arr
np.set_printoptions(precision=3)
rand_arr

array([[0.641, 0.244, 0.944],
       [0.171, 0.548, 0.712],
       [0.711, 0.627, 0.963],
       [0.798, 0.121, 0.239],
       [0.159, 0.491, 0.433]])

In [44]:
#Limit the number of items printed in python numpy array a to a maximum of 6 elements
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [49]:
# np.set_printoptions(threshold=6)
# np.arange(15)
# np.set_printoptions(threshold=np.nan)
# a

In [50]:
# Import the iris dataset keeping the text intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)